#!/usr/bin/env python3
# =============================================================================
# SCRIPT METADATA (Generated by g_code)
# =============================================================================
"""
Step ID: step02
Step Name: standardize_variables
RQ: results/ch7/7.7.1
Generated: 2026-01-09

PURPOSE:
Convert all variables to T-scores (M=50, SD=10) for meaningful effect size comparison

EXPECTED INPUTS:
  - results/ch7/7.7.1/data/step01_merged_dataset.csv
    Columns: ['UID', 'theta_all_mean', 'ravlt_total', 'bvmt_total', 'ravlt_pct_ret', 'bvmt_pct_ret']
    Expected rows: ~95-100

EXPECTED OUTPUTS:
  - results/ch7/7.7.1/data/step02_standardized_data.csv
    Columns: ['UID', 'REMEMVR_T', 'RAVLT_T', 'BVMT_T', 'RAVLT_PctRet_T', 'BVMT_PctRet_T']
    Format: T-scored variables (M=50, SD=10 each)
    Expected rows: same as input

VALIDATION CRITERIA:
  - All T-scores have mean=50 (±0.01)
  - All T-scores have SD=10 (±0.01)
  - No missing values

g_code REASONING:
- Approach: Standardize each variable using sample mean/SD to T-score formula
- Why this approach: T-scores enable meaningful comparison of regression coefficients across different scales
- Data flow: Load → Calculate sample statistics → Apply T-score transform → Validate → Save
- Expected performance: <2 seconds

IMPLEMENTATION NOTES:
- Analysis tool: tools.data.standardize_to_t_scores (uses sample statistics, not population)
- Validation tool: tools.validation.validate_standardization
- Parameters: target_mean=50.0, target_sd=10.0
- Formula: T = 50 + 10 * ((X - mean(X)) / sd(X))
"""
# =============================================================================

import sys
from pathlib import Path
import pandas as pd
import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(PROJECT_ROOT))

from tools.data import standardize_to_t_scores
from tools.validation import validate_standardization

# =============================================================================
# Configuration
# =============================================================================

RQ_DIR = Path(__file__).resolve().parents[1]
LOG_FILE = RQ_DIR / "logs" / "step02_standardize_variables.log"

def log(msg):
    with open(LOG_FILE, 'a', encoding='utf-8') as f:
        f.write(f"{msg}\n")
        f.flush()
    print(msg, flush=True)

# =============================================================================
# Main Analysis
# =============================================================================

if __name__ == "__main__":
    try:
        log("[START] Step 02: Standardize Variables")

        # STEP 1: Load merged data
        log("[LOAD] Loading merged dataset...")
        input_path = RQ_DIR / 'data' / 'step01_merged_dataset.csv'
        df = pd.read_csv(input_path)
        log(f"[LOADED] {len(df)} rows, {len(df.columns)} cols")

        # STEP 2: Compute sample statistics and standardize
        log("[STANDARDIZE] Converting to T-scores (M=50, SD=10)...")

        # Standardize each variable using SAMPLE statistics
        df['REMEMVR_T'] = standardize_to_t_scores(
            scores=df['theta_all_mean'],
            population_mean=df['theta_all_mean'].mean(),
            population_sd=df['theta_all_mean'].std()
        )
        log(f"[INFO] REMEMVR_T: M={df['REMEMVR_T'].mean():.2f}, SD={df['REMEMVR_T'].std():.2f}")

        df['RAVLT_T'] = standardize_to_t_scores(
            scores=df['ravlt_total'],
            population_mean=df['ravlt_total'].mean(),
            population_sd=df['ravlt_total'].std()
        )
        log(f"[INFO] RAVLT_T: M={df['RAVLT_T'].mean():.2f}, SD={df['RAVLT_T'].std():.2f}")

        df['BVMT_T'] = standardize_to_t_scores(
            scores=df['bvmt_total'],
            population_mean=df['bvmt_total'].mean(),
            population_sd=df['bvmt_total'].std()
        )
        log(f"[INFO] BVMT_T: M={df['BVMT_T'].mean():.2f}, SD={df['BVMT_T'].std():.2f}")

        df['RAVLT_PctRet_T'] = standardize_to_t_scores(
            scores=df['ravlt_pct_ret'],
            population_mean=df['ravlt_pct_ret'].mean(),
            population_sd=df['ravlt_pct_ret'].std()
        )
        log(f"[INFO] RAVLT_PctRet_T: M={df['RAVLT_PctRet_T'].mean():.2f}, SD={df['RAVLT_PctRet_T'].std():.2f}")

        df['BVMT_PctRet_T'] = standardize_to_t_scores(
            scores=df['bvmt_pct_ret'],
            population_mean=df['bvmt_pct_ret'].mean(),
            population_sd=df['bvmt_pct_ret'].std()
        )
        log(f"[INFO] BVMT_PctRet_T: M={df['BVMT_PctRet_T'].mean():.2f}, SD={df['BVMT_PctRet_T'].std():.2f}")

        # STEP 3: Validate standardization
        log("[VALIDATION] Checking T-score properties...")

        validation_result = validate_standardization(
            df=df,
            column_names=['REMEMVR_T', 'RAVLT_T', 'BVMT_T', 'RAVLT_PctRet_T', 'BVMT_PctRet_T'],
            tolerance=0.01
        )

        if validation_result.get('valid', False):
            log(f"[PASS] Standardization validation passed")
        else:
            log(f"[WARNING] Standardization validation: {validation_result.get('message', 'Unknown issue')}")

        # STEP 4: Save standardized data
        log("[SAVE] Saving T-scored variables...")
        output_path = RQ_DIR / 'data' / 'step02_standardized_data.csv'

        # Select final columns
        df_output = df[['UID', 'REMEMVR_T', 'RAVLT_T', 'BVMT_T', 'RAVLT_PctRet_T', 'BVMT_PctRet_T']].copy()
        df_output.to_csv(output_path, index=False, encoding='utf-8')
        log(f"[SAVED] {output_path}")

        log("[SUCCESS] Step 02 complete")
        sys.exit(0)

    except Exception as e:
        log(f"[ERROR] {str(e)}")
        import traceback
        with open(LOG_FILE, 'a', encoding='utf-8') as f:
            traceback.print_exc(file=f)
        traceback.print_exc()
        sys.exit(1)
