#!/usr/bin/env python3
# =============================================================================
# SCRIPT METADATA (Generated by g_code)
# =============================================================================
"""
Step ID: step00
Step Name: Validate Cross-RQ Dependencies
RQ: results/ch6/6.9.6
Generated: 2026-01-19

PURPOSE:
Verify required dependencies from Ch5 5.1.2 and Ch6 6.1.1 exist before proceeding
with practice effect differential analysis. Ensures accuracy baseline and confidence
trajectories are available for comparison.

EXPECTED INPUTS:
- results/ch5/5.1.2/status.yaml
  Purpose: Verify RQ completion status
- results/ch5/5.1.2/data/step07_practice_effect_by_phase.csv
  Columns: ['phase', 'slope', 'se', 'p_value']
  Purpose: Accuracy saturation baseline (5.7x ratio)
- results/ch6/6.1.1/status.yaml
  Purpose: Verify RQ completion status
- results/ch6/6.1.1/data/step03_theta_confidence.csv
  Columns: ['composite_ID', 'theta_All', 'se_All']
  Expected rows: ~400 (100 UIDs x 4 tests)
- results/ch6/6.1.1/data/step00_tsvr_mapping.csv
  Columns: ['composite_ID', 'TSVR_hours', 'test']
  Expected rows: ~400

EXPECTED OUTPUTS:
- results/ch6/6.9.6/data/step00_dependency_validation.txt
  Format: Text validation log
  Content: Pass/fail for each dependency check

VALIDATION CRITERIA:
- Both RQs completed successfully (status.yaml shows rq_results: success)
- All required files exist and meet minimum size (>100 bytes)
- Accuracy file contains 5.7x saturation ratio documentation
- Confidence data has 400 rows (100 UIDs x 4 tests)

g_code REASONING:
- Approach: Standard library validation (pathlib, pandas, yaml) with comprehensive
  error reporting for each dependency check
- Why this approach: Derived RQ requires upstream completion; explicit validation
  prevents wasted computation if dependencies missing
- Data flow: No transformations; pure validation with detailed logging
- Expected performance: ~5-10 seconds

IMPLEMENTATION NOTES:
- Analysis tool: stdlib (pathlib.Path.exists, pandas.read_csv, yaml.safe_load)
- Validation tool: tools.validation.check_file_exists
- Parameters: Minimum file size 100 bytes for non-empty check
"""
# =============================================================================

import sys
from pathlib import Path
import pandas as pd
import yaml
from typing import Dict, List, Tuple, Any
import traceback

# Add project root to path for imports
# CRITICAL: RQ scripts are in results/chX/rqY/code/ (4 levels deep from project root)
PROJECT_ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(PROJECT_ROOT))

# Import validation tool
from tools.validation import check_file_exists

# =============================================================================
# Configuration
# =============================================================================

RQ_DIR = Path(__file__).resolve().parents[1]  # results/ch6/6.9.6
LOG_FILE = RQ_DIR / "logs" / "step00_validate_dependencies.log"
OUTPUT_FILE = RQ_DIR / "data" / "step00_dependency_validation.txt"

# Dependency paths (absolute)
CH5_5_1_2_STATUS = PROJECT_ROOT / "results" / "ch5" / "5.1.2" / "status.yaml"
CH5_5_1_2_PRACTICE = PROJECT_ROOT / "results" / "ch5" / "5.1.2" / "data" / "step07_practice_effect_by_phase.csv"
CH6_6_1_1_STATUS = PROJECT_ROOT / "results" / "ch6" / "6.1.1" / "status.yaml"
CH6_6_1_1_THETA = PROJECT_ROOT / "results" / "ch6" / "6.1.1" / "data" / "step03_theta_confidence.csv"
CH6_6_1_1_TSVR = PROJECT_ROOT / "results" / "ch6" / "6.1.1" / "data" / "step00_tsvr_mapping.csv"

# =============================================================================
# FOLDER CONVENTIONS (MANDATORY - NO EXCEPTIONS)
# =============================================================================
#
# code/   : ONLY .py scripts (generated by g_code)
# data/   : ALL data outputs (.csv, .pkl, .txt) - ANY file produced by code
# logs/   : ONLY .log files - execution logs
# plots/  : ONLY image files (.png, .pdf, .svg) - actual plot images
# results/: ONLY final summary reports (.md, .html)
# docs/   : RQ documentation (concept, plan, analysis specs)
#
# NAMING CONVENTION (MANDATORY):
# ALL files in data/ and logs/ MUST be prefixed with step number:
#   - stepXX_descriptive_name.csv
#   - stepXX_descriptive_name.log

# =============================================================================
# Logging Function
# =============================================================================

def log(msg):
    """Write to both log file and console."""
    with open(LOG_FILE, 'a', encoding='utf-8') as f:
        f.write(f"{msg}\n")
    print(msg)

# =============================================================================
# Main Validation
# =============================================================================

if __name__ == "__main__":
    try:
        log("[START] Step 0: Validate Cross-RQ Dependencies")
        log("=" * 80)

        # Track validation results
        checks_passed = []
        checks_failed = []

        # =====================================================================
        # CHECK 1: Ch5 5.1.2 Status
        # =====================================================================
        log("\n[CHECK 1] Ch5 5.1.2 completion status...")

        if not CH5_5_1_2_STATUS.exists():
            msg = f"FAIL: Ch5 5.1.2 status.yaml not found at {CH5_5_1_2_STATUS}"
            log(msg)
            checks_failed.append("Ch5 5.1.2 status.yaml")
        else:
            with open(CH5_5_1_2_STATUS, 'r', encoding='utf-8') as f:
                status_data = yaml.safe_load(f)

            rq_results_status = status_data.get('rq_results', 'unknown')
            if rq_results_status == 'success':
                log(f"[PASS] Ch5 5.1.2: rq_results = success")
                checks_passed.append("Ch5 5.1.2 status")
            else:
                msg = f"FAIL: Ch5 5.1.2 rq_results = {rq_results_status} (expected: success)"
                log(msg)
                checks_failed.append("Ch5 5.1.2 completion")

        # =====================================================================
        # CHECK 2: Ch5 5.1.2 Practice Effect Data
        # =====================================================================
        log("\n[CHECK 2] Ch5 5.1.2 practice effect baseline...")

        result = check_file_exists(CH5_5_1_2_PRACTICE, min_size_bytes=100)
        if result['valid']:
            log(f"[PASS] Found: {CH5_5_1_2_PRACTICE}")
            log(f"        Size: {result['size_bytes']} bytes")

            # Verify file structure
            df_practice = pd.read_csv(CH5_5_1_2_PRACTICE, encoding='utf-8')
            required_cols = ['phase', 'slope', 'se', 'p_value']
            missing_cols = [col for col in required_cols if col not in df_practice.columns]

            if missing_cols:
                msg = f"FAIL: Ch5 5.1.2 practice file missing columns: {missing_cols}"
                log(msg)
                checks_failed.append("Ch5 5.1.2 practice columns")
            else:
                log(f"[PASS] Practice file has {len(df_practice)} rows, required columns present")

                # Document saturation ratio (for reference)
                if len(df_practice) >= 2:
                    # Expect rows: Practice T1->T2, Forgetting T2->T4, Difference
                    practice_row = df_practice[df_practice['phase'].str.contains('T1', na=False)]
                    forgetting_row = df_practice[df_practice['phase'].str.contains('T2', na=False) & df_practice['phase'].str.contains('T4', na=False)]

                    if len(practice_row) > 0 and len(forgetting_row) > 0:
                        ratio = abs(practice_row['slope'].values[0]) / abs(forgetting_row['slope'].values[0])
                        log(f"        Accuracy saturation ratio: {ratio:.2f}x (expected ~5.7)")

                checks_passed.append("Ch5 5.1.2 practice data")
        else:
            log(f"[FAIL] {result['message']}")
            checks_failed.append("Ch5 5.1.2 practice file")

        # =====================================================================
        # CHECK 3: Ch6 6.1.1 Status
        # =====================================================================
        log("\n[CHECK 3] Ch6 6.1.1 completion status...")

        if not CH6_6_1_1_STATUS.exists():
            msg = f"FAIL: Ch6 6.1.1 status.yaml not found at {CH6_6_1_1_STATUS}"
            log(msg)
            checks_failed.append("Ch6 6.1.1 status.yaml")
        else:
            with open(CH6_6_1_1_STATUS, 'r', encoding='utf-8') as f:
                status_data = yaml.safe_load(f)

            rq_results_status = status_data.get('rq_results', 'unknown')
            if rq_results_status == 'success':
                log(f"[PASS] Ch6 6.1.1: rq_results = success")
                checks_passed.append("Ch6 6.1.1 status")
            else:
                msg = f"FAIL: Ch6 6.1.1 rq_results = {rq_results_status} (expected: success)"
                log(msg)
                checks_failed.append("Ch6 6.1.1 completion")

        # =====================================================================
        # CHECK 4: Ch6 6.1.1 Theta Confidence Scores
        # =====================================================================
        log("\n[CHECK 4] Ch6 6.1.1 confidence theta scores...")

        result = check_file_exists(CH6_6_1_1_THETA, min_size_bytes=100)
        if result['valid']:
            log(f"[PASS] Found: {CH6_6_1_1_THETA}")
            log(f"        Size: {result['size_bytes']} bytes")

            # Verify file structure
            df_theta = pd.read_csv(CH6_6_1_1_THETA, encoding='utf-8')
            required_cols = ['composite_ID', 'theta_All', 'se_All']
            missing_cols = [col for col in required_cols if col not in df_theta.columns]

            if missing_cols:
                msg = f"FAIL: Ch6 6.1.1 theta file missing columns: {missing_cols}"
                log(msg)
                checks_failed.append("Ch6 6.1.1 theta columns")
            else:
                log(f"[PASS] Theta file has {len(df_theta)} rows, required columns present")

                # Verify row count (expect 400: 100 UIDs x 4 tests)
                if len(df_theta) < 300 or len(df_theta) > 500:
                    log(f"[WARNING] Expected ~400 rows, found {len(df_theta)}")

                # Verify participant count
                df_theta['UID'] = df_theta['composite_ID'].str.split('_').str[0]
                n_uids = df_theta['UID'].nunique()
                log(f"        Participants: {n_uids} unique UIDs")

                if n_uids < 90 or n_uids > 110:
                    log(f"[WARNING] Expected ~100 participants, found {n_uids}")

                checks_passed.append("Ch6 6.1.1 theta data")
        else:
            log(f"[FAIL] {result['message']}")
            checks_failed.append("Ch6 6.1.1 theta file")

        # =====================================================================
        # CHECK 5: Ch6 6.1.1 TSVR Mapping
        # =====================================================================
        log("\n[CHECK 5] Ch6 6.1.1 TSVR time mapping...")

        result = check_file_exists(CH6_6_1_1_TSVR, min_size_bytes=100)
        if result['valid']:
            log(f"[PASS] Found: {CH6_6_1_1_TSVR}")
            log(f"        Size: {result['size_bytes']} bytes")

            # Verify file structure
            df_tsvr = pd.read_csv(CH6_6_1_1_TSVR, encoding='utf-8')
            required_cols = ['composite_ID', 'TSVR_hours', 'test']
            missing_cols = [col for col in required_cols if col not in df_tsvr.columns]

            if missing_cols:
                msg = f"FAIL: Ch6 6.1.1 TSVR file missing columns: {missing_cols}"
                log(msg)
                checks_failed.append("Ch6 6.1.1 TSVR columns")
            else:
                log(f"[PASS] TSVR file has {len(df_tsvr)} rows, required columns present")

                # Verify row count
                if len(df_tsvr) < 300 or len(df_tsvr) > 500:
                    log(f"[WARNING] Expected ~400 rows, found {len(df_tsvr)}")

                # Verify test labels
                unique_tests = sorted(df_tsvr['test'].unique())
                log(f"        Test labels: {unique_tests}")

                checks_passed.append("Ch6 6.1.1 TSVR data")
        else:
            log(f"[FAIL] {result['message']}")
            checks_failed.append("Ch6 6.1.1 TSVR file")

        # =====================================================================
        # SUMMARY
        # =====================================================================
        log("\n" + "=" * 80)
        log("[VALIDATION SUMMARY]")
        log(f"  Checks passed: {len(checks_passed)}")
        log(f"  Checks failed: {len(checks_failed)}")

        if checks_passed:
            log("\n[PASSED CHECKS]")
            for check in checks_passed:
                log(f"  - {check}")

        if checks_failed:
            log("\n[FAILED CHECKS]")
            for check in checks_failed:
                log(f"  - {check}")

        # =====================================================================
        # SAVE VALIDATION REPORT
        # =====================================================================
        log(f"\n[SAVE] Writing validation report to {OUTPUT_FILE}...")

        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write("# RQ 6.9.6 Dependency Validation Report\n")
            f.write("=" * 80 + "\n\n")

            f.write("## Ch5 5.1.2 (Accuracy Practice Decomposition)\n")
            if "Ch5 5.1.2 status" in checks_passed and "Ch5 5.1.2 practice data" in checks_passed:
                f.write("Status: PASS\n")
                f.write(f"- status.yaml: rq_results = success\n")
                f.write(f"- practice_effect_by_phase.csv: {CH5_5_1_2_PRACTICE}\n")
            else:
                f.write("Status: FAIL\n")
                if "Ch5 5.1.2 status.yaml" in checks_failed:
                    f.write("- status.yaml: NOT FOUND\n")
                if "Ch5 5.1.2 completion" in checks_failed:
                    f.write("- status.yaml: rq_results != success\n")
                if "Ch5 5.1.2 practice file" in checks_failed:
                    f.write("- practice_effect_by_phase.csv: NOT FOUND\n")

            f.write("\n## Ch6 6.1.1 (Confidence Trajectories)\n")
            if "Ch6 6.1.1 status" in checks_passed and "Ch6 6.1.1 theta data" in checks_passed and "Ch6 6.1.1 TSVR data" in checks_passed:
                f.write("Status: PASS\n")
                f.write(f"- status.yaml: rq_results = success\n")
                f.write(f"- theta_confidence.csv: {CH6_6_1_1_THETA} ({len(df_theta)} rows)\n")
                f.write(f"- tsvr_mapping.csv: {CH6_6_1_1_TSVR} ({len(df_tsvr)} rows)\n")
            else:
                f.write("Status: FAIL\n")
                if "Ch6 6.1.1 status.yaml" in checks_failed:
                    f.write("- status.yaml: NOT FOUND\n")
                if "Ch6 6.1.1 completion" in checks_failed:
                    f.write("- status.yaml: rq_results != success\n")
                if "Ch6 6.1.1 theta file" in checks_failed:
                    f.write("- theta_confidence.csv: NOT FOUND\n")
                if "Ch6 6.1.1 TSVR file" in checks_failed:
                    f.write("- tsvr_mapping.csv: NOT FOUND\n")

            f.write("\n" + "=" * 80 + "\n")
            f.write(f"FINAL RESULT: {'PASS - All dependencies validated' if not checks_failed else 'FAIL - Missing dependencies'}\n")

        log(f"[SAVED] {OUTPUT_FILE}")

        # =====================================================================
        # EXIT STATUS
        # =====================================================================
        if checks_failed:
            log("\n[ERROR] Dependency validation FAILED")
            log("Action: Cannot proceed to Step 1 - fix dependencies and re-run Step 0")
            sys.exit(1)
        else:
            log("\n[SUCCESS] All dependencies validated - ready for Step 1")
            sys.exit(0)

    except Exception as e:
        log(f"[ERROR] {str(e)}")
        log("[TRACEBACK] Full error details:")
        with open(LOG_FILE, 'a', encoding='utf-8') as f:
            traceback.print_exc(file=f)
        traceback.print_exc()
        sys.exit(1)
