#!/usr/bin/env python3
# =============================================================================
# SCRIPT METADATA (Generated by g_code)
# =============================================================================
"""
Step ID: step00
Step Name: Get Data (Load RQ 5.1.1 Outputs)
RQ: results/ch5/5.1.2
Generated: 2025-11-28

PURPOSE:
Load theta scores, TSVR mapping, and best continuous model from RQ 5.1.1 outputs.
This step establishes the data dependencies for RQ 5.1.2 two-phase forgetting analysis.

EXPECTED INPUTS:
  - results/ch5/5.1.1/data/step02_theta_long.csv
    Columns: ['UID', 'test', 'domain', 'theta']
    Format: Long-format theta scores from IRT calibration Pass 2
    Expected rows: ~1200 (100 participants x 4 tests x 3 domains)
    Source: RQ 5.1.1 Step 2 (IRT calibration Pass 2 theta scores)

  - results/ch5/5.1.1/data/step00_tsvr_mapping.csv
    Columns: ['UID', 'test', 'TSVR_hours']
    Format: Time since VR encoding in hours (Decision D070)
    Expected rows: ~400 (100 participants x 4 tests)
    Source: RQ 5.1.1 Step 0 (TSVR extraction from master.xlsx)

  - results/ch5/5.1.1/data/step03_best_model.pkl
    Format: Pickled MixedLMResults object
    Source: RQ 5.1.1 Step 3 (best continuous model selection by AIC)

EXPECTED OUTPUTS:
  - data/step00_theta_tsvr.csv
    Columns: ['UID', 'test', 'TSVR_hours', 'theta']
    Format: Merged theta + TSVR, domain-collapsed (mean across What/Where/When)
    Expected rows: ~400 (100 participants x 4 tests)

  - data/step00_best_continuous_aic.txt
    Format: Single numeric value (AIC from RQ 5.1.1 best continuous model)
    Purpose: For Step 3 AIC comparison (piecewise vs continuous)

  - data/step00_rq57_convergence.txt
    Format: Text report of RQ 5.1.1 model convergence status + random effects structure
    Purpose: CRITICAL for interpreting AIC comparison validity in Step 3

VALIDATION CRITERIA:
  - All 3 RQ 5.1.1 dependency files exist
  - No file size = 0 (files not empty)
  - Merge produces ~400 rows (no unexpected data loss)
  - No NaN in theta or TSVR_hours after merge
  - AIC value is positive and reasonable (10000-20000 range)

g_code REASONING:
- Approach: Cross-RQ data dependency resolution with convergence validation
- Why this approach: RQ 5.1.2 builds on RQ 5.1.1 continuous model results. Must validate
  RQ 5.1.1 convergence status BEFORE using its AIC for comparison (Step 3). Fallback
  random effects in RQ 5.1.1 would invalidate direct AIC comparison.
- Data flow: RQ 5.1.1 outputs (theta, TSVR, model) -> domain collapse -> merged dataset
  for piecewise modeling (Steps 2-3)
- Expected performance: ~seconds (file I/O only, no computation)

IMPLEMENTATION NOTES:
- Analysis tool: stdlib (pickle.load, pd.read_csv, pd.merge, pd.groupby)
- Validation tool: tools.validation.check_file_exists
- Parameters: Domain aggregation = mean, merge keys = (UID, test)
- CRITICAL: Load step03_best_model.pkl FIRST to validate convergence before proceeding
- CRITICAL: Document random effects structure (affects AIC comparison interpretation)
"""
# =============================================================================

import sys
from pathlib import Path
import pandas as pd
import traceback

# Add project root to path for imports
# CRITICAL: RQ scripts are in results/chX/rqY/code/ (4 levels deep from project root)
# Path hierarchy from script location:
#   parents[0] = code/ (immediate parent)
#   parents[1] = rqY/
#   parents[2] = chX/
#   parents[3] = results/
#   parents[4] = REMEMVR/ (project root - THIS is what we need for imports)
PROJECT_ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(PROJECT_ROOT))

# Import validation tool
from tools.validation import check_file_exists

# =============================================================================
# Configuration
# =============================================================================

RQ_DIR = Path(__file__).resolve().parents[1]  # results/ch5/5.1.2 (derived from script location)
LOG_FILE = RQ_DIR / "logs" / "step00_get_data.log"

# RQ 5.1.1 dependency paths (absolute)
RQ7_DIR = PROJECT_ROOT / "results" / "ch5" / "rq7"
RQ7_LMM_INPUT_FILE = RQ7_DIR / "data" / "step04_lmm_input.csv"  # Has UID, test, Theta, TSVR_hours
RQ7_MODEL_COMPARISON_FILE = RQ7_DIR / "results" / "step05_model_comparison.csv"  # Has best model AIC

# =============================================================================
# FOLDER CONVENTIONS (MANDATORY - NO EXCEPTIONS)
# =============================================================================
#
# code/   : ONLY .py scripts (generated by g_code)
# data/   : ALL data outputs (.csv, .pkl, .txt) - ANY file produced by code
# logs/   : ONLY .log files - execution logs
# plots/  : ONLY image files (.png, .pdf, .svg) - actual plot images
# results/: ONLY final summary reports (.md, .html)
# docs/   : RQ documentation (concept, plan, analysis specs)
#
# NAMING CONVENTION (MANDATORY):
# ALL files in data/ and logs/ MUST be prefixed with step number:
#   - stepXX_descriptive_name.csv
#   - stepXX_descriptive_name.pkl
#   - stepXX_descriptive_name.log
#
# Examples:
#   CORRECT: data/step00_theta_tsvr.csv
#   CORRECT: data/step00_best_continuous_aic.txt
#   WRONG:   results/theta_tsvr.csv  (wrong folder + no prefix)
#   WRONG:   data/theta_tsvr.csv     (missing step prefix)

# =============================================================================
# Logging Function
# =============================================================================

def log(msg):
    """Write to both log file and console."""
    with open(LOG_FILE, 'a', encoding='utf-8') as f:
        f.write(f"{msg}\n")
    print(msg)

# =============================================================================
# Main Analysis
# =============================================================================

if __name__ == "__main__":
    try:
        log("[START] Step 0: Get Data (Load RQ 5.1.1 Outputs)")

        # =========================================================================
        # STEP 1: Validate RQ 5.1.1 Dependency Files Exist
        # =========================================================================
        # Expected: All 3 files from RQ 5.1.1 (theta, TSVR, best model)
        # Purpose: Fail-fast if RQ 5.1.1 incomplete (EXPECTATIONS ERROR)

        log("[VALIDATION] Checking RQ 5.1.1 dependency files exist...")

        # Check RQ 5.1.1 LMM input file exists
        validation_result = check_file_exists(
            file_path=str(RQ7_LMM_INPUT_FILE),
            min_size_bytes=1000  # Should be ~35KB
        )

        if not validation_result.get('valid', False):
            raise FileNotFoundError(
                f"EXPECTATIONS ERROR: RQ 5.1.1 dependency missing or invalid: {RQ7_LMM_INPUT_FILE}\n"
                f"Validation message: {validation_result.get('message', 'unknown')}\n"
                f"RQ 5.1.1 must complete successfully before RQ 5.1.2 can proceed."
            )

        log(f"[PASS] Dependency exists: {RQ7_LMM_INPUT_FILE.name} ({validation_result['size_bytes']} bytes)")

        # =========================================================================
        # STEP 2: Load RQ 5.1.1 LMM Input Data
        # =========================================================================
        # RQ 5.1.1 step04_lmm_input.csv already has UID, test, Theta, TSVR_hours merged
        # We just need to select relevant columns and rename Theta -> theta

        log("[LOAD] Loading RQ 5.1.1 LMM input data...")
        rq7_data = pd.read_csv(RQ7_LMM_INPUT_FILE, encoding='utf-8')
        log(f"[LOADED] {RQ7_LMM_INPUT_FILE.name} ({len(rq7_data)} rows, {len(rq7_data.columns)} cols)")
        log(f"[INFO] Columns: {list(rq7_data.columns)}")

        # Load RQ 5.1.1 model comparison results (for AIC)
        log("[LOAD] Loading RQ 5.1.1 model comparison...")
        rq7_models = pd.read_csv(RQ7_MODEL_COMPARISON_FILE, encoding='utf-8')
        log(f"[LOADED] {RQ7_MODEL_COMPARISON_FILE.name} ({len(rq7_models)} models)")

        # Get best model (lowest AIC = delta_AIC == 0)
        best_model = rq7_models[rq7_models['delta_AIC'] == 0].iloc[0]
        rq7_aic = best_model['AIC']
        rq7_model_name = best_model['model_name']
        log(f"[INFO] RQ 5.1.1 best model: {rq7_model_name} (AIC = {rq7_aic:.2f})")

        # =========================================================================
        # STEP 3: Extract relevant columns and rename
        # =========================================================================
        # RQ 5.1.1 has: composite_ID, UID, test, Theta, SE, TSVR_hours, Days, Days_squared, log_Days_plus1
        # RQ 5.1.2 needs: UID, test, theta (lowercase), TSVR_hours

        log("[TRANSFORM] Selecting columns (UID, test, Theta, TSVR_hours) and renaming...")
        theta_tsvr = rq7_data[['UID', 'test', 'Theta', 'TSVR_hours']].copy()
        theta_tsvr.rename(columns={'Theta': 'theta'}, inplace=True)
        log(f"[INFO] Extracted shape: {theta_tsvr.shape}")
        log(f"[INFO] Columns: {list(theta_tsvr.columns)}")

        # =========================================================================
        # STEP 4: Validation
        # =========================================================================
        # Check row count (expect ~400: 100 participants x 4 tests)
        expected_rows_min = 380
        expected_rows_max = 420

        if len(theta_tsvr) < expected_rows_min:
            log(f"[WARNING] Data has {len(theta_tsvr)} rows (expected ~400)")
        elif len(theta_tsvr) > expected_rows_max:
            log(f"[WARNING] Data has {len(theta_tsvr)} rows (expected ~400)")
        else:
            log(f"[PASS] Row count reasonable: {len(theta_tsvr)} rows")

        # Check for NaN values
        nan_theta = theta_tsvr['theta'].isna().sum()
        nan_tsvr = theta_tsvr['TSVR_hours'].isna().sum()

        if nan_theta > 0:
            raise ValueError(
                f"[FAIL] Merged data contains {nan_theta} NaN values in theta column\n"
                f"Check RQ 5.1.1 theta scores for missing values"
            )

        if nan_tsvr > 0:
            raise ValueError(
                f"[FAIL] Merged data contains {nan_tsvr} NaN values in TSVR_hours column\n"
                f"Check RQ 5.1.1 TSVR mapping for missing values"
            )

        log(f"[PASS] No NaN values in theta or TSVR_hours")

        # =========================================================================
        # STEP 6: Save Outputs
        # =========================================================================
        # Save merged theta + TSVR dataset
        # Save RQ 5.1.1 AIC value (for Step 3 comparison)
        # Save RQ 5.1.1 convergence status (CRITICAL for interpretation)

        output_theta_tsvr = RQ_DIR / "data" / "step00_theta_tsvr.csv"
        log(f"[SAVE] Saving merged theta + TSVR to {output_theta_tsvr.name}...")
        theta_tsvr.to_csv(output_theta_tsvr, index=False, encoding='utf-8')
        log(f"[SAVED] {output_theta_tsvr.name} ({len(theta_tsvr)} rows, {len(theta_tsvr.columns)} cols)")

        output_aic = RQ_DIR / "data" / "step00_best_continuous_aic.txt"
        log(f"[SAVE] Saving RQ 5.1.1 AIC to {output_aic.name}...")
        with open(output_aic, 'w', encoding='utf-8') as f:
            f.write(f"{rq7_aic:.6f}\n")
        log(f"[SAVED] {output_aic.name} (AIC = {rq7_aic:.2f})")

        output_convergence = RQ_DIR / "data" / "step00_rq57_convergence.txt"
        log(f"[SAVE] Saving RQ 5.1.1 model info to {output_convergence.name}...")
        with open(output_convergence, 'w', encoding='utf-8') as f:
            f.write(f"RQ 5.1.1 Best Continuous Model Information\n")
            f.write(f"=" * 60 + "\n")
            f.write(f"Best model: {rq7_model_name}\n")
            f.write(f"AIC: {rq7_aic:.6f}\n")
            f.write(f"\n")
            f.write(f"INTERPRETATION FOR RQ 5.1.2 STEP 3:\n")
            f.write(f"-" * 60 + "\n")
            f.write(f"RQ 5.1.1 completed successfully with {rq7_model_name} as best model.\n")
            f.write(f"AIC comparison in Step 3 uses this value as reference.\n")
        log(f"[SAVED] {output_convergence.name}")

        log("[SUCCESS] Step 0 complete")
        log(f"[INFO] Outputs:")
        log(f"  - {output_theta_tsvr.name}: {len(theta_tsvr)} rows (merged theta + TSVR)")
        log(f"  - {output_aic.name}: AIC = {rq7_aic:.2f} (for Step 3 comparison)")
        log(f"  - {output_convergence.name}: Convergence status (CRITICAL for interpretation)")

        sys.exit(0)

    except Exception as e:
        log(f"[ERROR] {str(e)}")
        log("[TRACEBACK] Full error details:")
        with open(LOG_FILE, 'a', encoding='utf-8') as f:
            traceback.print_exc(file=f)
        traceback.print_exc()
        sys.exit(1)
