#!/usr/bin/env python3
# =============================================================================
# SCRIPT METADATA (Generated by g_code)
# =============================================================================
"""
Step ID: step00
Step Name: validate_dependencies
RQ: results/ch7/7.7.2
Generated: 2026-01-09

PURPOSE:
Validate Ch5 5.1.1 theta scores and dfnonvr.csv data exist before proceeding.
Ensures all required dependencies are in place for discrepancy analysis.

EXPECTED INPUTS:
  - results/ch5/5.1.1/status.yaml
    Description: Ch5 5.1.1 completion status
    Expected: rq_results.status = 'success'
  - results/ch5/5.1.1/data/step03_theta_scores.csv
    Columns: ['UID', 'test', 'Theta_All']
    Description: Omnibus theta scores from Ch5
    Expected rows: ~400 (100 participants x 4 sessions)
  - data/dfnonvr.csv
    Columns: ['UID', 'age', 'education', 'vr-exposure', 'nart-score', 'bvmt-total-recall', 'ravlt-trial-1-score', ...]
    Description: Participant demographics and cognitive test data
    Expected rows: ~100

EXPECTED OUTPUTS:
  - results/ch7/7.7.2/data/step00_dependency_validation.txt
    Description: Validation results summary
    Format: Text report with file paths and participant counts

VALIDATION CRITERIA:
  - Ch5 5.1.1 status shows rq_results: success
  - Theta scores file located with ~100 unique participants
  - dfnonvr.csv accessible with required columns
  - No critical missing dependencies

g_code REASONING:
- Approach: Check file existence, load status.yaml, verify data structure
- Why this approach: Fail-fast strategy - detect missing dependencies before computation
- Data flow: Validate Ch5 completion -> Locate theta file -> Verify dfnonvr.csv -> Report status
- Expected performance: <5 seconds (file operations only)

IMPLEMENTATION NOTES:
- Analysis tool: stdlib file operations + yaml + pandas
- Validation tool: tools.validation.validate_data_format
- Parameters: expected_participants=100, required_ch5_status='success'
- Column name handling: Ch5 theta file may use 'Theta_All' or 'theta_all' (check both)
"""
# =============================================================================

import sys
from pathlib import Path
import pandas as pd
import yaml
from typing import Dict, List, Any
import traceback

# Add project root to path for imports
# CRITICAL: RQ scripts are in results/ch7/7.7.2/code/ (4 levels deep from project root)
PROJECT_ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(PROJECT_ROOT))

# Import validation tool
from tools.validation import validate_data_format

# =============================================================================
# Configuration
# =============================================================================

RQ_DIR = Path(__file__).resolve().parents[1]  # results/ch7/7.7.2
LOG_FILE = RQ_DIR / "logs" / "step00_validate_dependencies.log"

# =============================================================================
# FOLDER CONVENTIONS (MANDATORY - NO EXCEPTIONS)
# =============================================================================
#
# code/   : ONLY .py scripts
# data/   : ALL data outputs (.csv, .pkl, .txt)
# logs/   : ONLY .log files
# plots/  : ONLY image files (.png, .pdf, .svg)
# results/: ONLY final reports (.md, .html)
# docs/   : RQ documentation
#
# NAMING CONVENTION:
# ALL files in data/ and logs/ MUST be prefixed with step number:
#   - stepXX_descriptive_name.csv
#   - stepXX_descriptive_name.log
#
# =============================================================================

# =============================================================================
# Logging Function
# =============================================================================

def log(msg):
    """Write to both log file and console."""
    with open(LOG_FILE, 'a', encoding='utf-8') as f:
        f.write(f"{msg}\n")
        f.flush()
    print(msg, flush=True)

# =============================================================================
# Main Analysis
# =============================================================================

if __name__ == "__main__":
    try:
        log("[START] Step 00: Validate Dependencies")

        # =========================================================================
        # STEP 1: Validate Ch5 5.1.1 Status
        # =========================================================================
        log("[CHECK] Validating Ch5 5.1.1 completion status...")

        ch5_status_path = PROJECT_ROOT / "results" / "ch5" / "5.1.1" / "status.yaml"
        if not ch5_status_path.exists():
            raise FileNotFoundError(f"Ch5 5.1.1 status file not found: {ch5_status_path}")

        with open(ch5_status_path, 'r', encoding='utf-8') as f:
            status = yaml.safe_load(f)

        # Handle both dict and string formats (from gcode_lessons.md Bug #5)
        rq_results_status = status.get('rq_results', {})
        if isinstance(rq_results_status, dict):
            actual_status = rq_results_status.get('status')
        elif isinstance(rq_results_status, str):
            actual_status = rq_results_status
        else:
            actual_status = 'unknown'

        if actual_status != 'success':
            raise ValueError(f"Ch5 5.1.1 not completed - rq_results status is '{actual_status}', expected 'success'")

        log(f"[PASS] Ch5 5.1.1 status: {actual_status}")

        # =========================================================================
        # STEP 2: Locate Theta Scores File
        # =========================================================================
        log("[CHECK] Locating Ch5 5.1.1 theta scores file...")

        # Try multiple possible locations
        theta_candidates = [
            PROJECT_ROOT / "results" / "ch5" / "5.1.1" / "data" / "step03_theta_scores.csv",
            PROJECT_ROOT / "results" / "ch5" / "5.1.1" / "data" / "theta_omnibus_scores.csv",
            PROJECT_ROOT / "results" / "ch5" / "5.1.1" / "data" / "theta_all_scores.csv"
        ]

        theta_path = None
        for candidate in theta_candidates:
            if candidate.exists():
                theta_path = candidate
                break

        if theta_path is None:
            raise FileNotFoundError(f"Ch5 5.1.1 theta scores file not found. Tried: {[str(c) for c in theta_candidates]}")

        log(f"[FOUND] Theta scores file: {theta_path.relative_to(PROJECT_ROOT)}")

        # Load and validate theta file structure
        theta_df = pd.read_csv(theta_path)

        # Find theta column (may be 'Theta_All' or 'theta_all')
        theta_col = None
        for col in theta_df.columns:
            if col.lower() == 'theta_all':
                theta_col = col
                break

        if theta_col is None:
            raise ValueError(f"No omnibus theta column found in {theta_path}. Available columns: {theta_df.columns.tolist()}")

        # Verify required columns
        required_theta_cols = ['UID', 'test', theta_col]
        missing_cols = [col for col in required_theta_cols if col not in theta_df.columns]
        if missing_cols:
            raise ValueError(f"Missing required columns in theta file: {missing_cols}")

        n_theta_rows = len(theta_df)
        n_theta_participants = theta_df['UID'].nunique()

        log(f"[PASS] Theta file structure valid: {n_theta_rows} rows, {n_theta_participants} unique participants")
        log(f"[INFO] Theta column name: '{theta_col}'")

        # =========================================================================
        # STEP 3: Validate dfnonvr.csv
        # =========================================================================
        log("[CHECK] Validating dfnonvr.csv data file...")

        dfnonvr_path = PROJECT_ROOT / "data" / "dfnonvr.csv"
        if not dfnonvr_path.exists():
            raise FileNotFoundError(f"Prepared data file not found: {dfnonvr_path}")

        dfnonvr_df = pd.read_csv(dfnonvr_path)

        # Verify key columns exist (exact names from DATA_DICTIONARY.md)
        required_demo_cols = ['UID', 'age', 'education', 'vr-exposure']
        required_ravlt_cols = [
            'ravlt-trial-1-score', 'ravlt-trial-2-score', 'ravlt-trial-3-score',
            'ravlt-trial-4-score', 'ravlt-trial-5-score'
        ]

        all_required = required_demo_cols + required_ravlt_cols
        missing_cols = [col for col in all_required if col not in dfnonvr_df.columns]

        if missing_cols:
            raise ValueError(f"Missing required columns in dfnonvr.csv: {missing_cols}")

        n_demo_participants = len(dfnonvr_df)

        log(f"[PASS] dfnonvr.csv structure valid: {n_demo_participants} participants")
        log(f"[PASS] All required demographic and RAVLT columns present")

        # =========================================================================
        # STEP 4: Validation Tool Check
        # =========================================================================
        log("[VALIDATION] Running validate_data_format on theta file...")

        validation_result = validate_data_format(
            df=theta_df,
            required_cols=required_theta_cols
        )

        if not validation_result.get('valid', False):
            log(f"[WARNING] Theta file validation warnings: {validation_result}")
        else:
            log("[PASS] Theta file validation successful")

        # =========================================================================
        # STEP 5: Save Validation Results
        # =========================================================================
        output_file = RQ_DIR / "data" / "step00_dependency_validation.txt"

        validation_summary = f"""DEPENDENCY VALIDATION RESULTS
Generated: {pd.Timestamp.now().isoformat()}

Ch5 5.1.1 Status:
  Status File: {ch5_status_path.relative_to(PROJECT_ROOT)}
  RQ Results Status: {actual_status}
  Validation: PASS

Theta Scores File:
  Path: {theta_path.relative_to(PROJECT_ROOT)}
  Theta Column: {theta_col}
  Total Rows: {n_theta_rows}
  Unique Participants: {n_theta_participants}
  Validation: PASS

dfnonvr.csv File:
  Path: {dfnonvr_path.relative_to(PROJECT_ROOT)}
  Total Participants: {n_demo_participants}
  Required Columns Present: {len(all_required)}
  Validation: PASS

Summary:
  All dependencies validated successfully
  Ready to proceed with discrepancy analysis
"""

        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(validation_summary)

        log(f"[SAVED] Validation results: {output_file.relative_to(RQ_DIR)}")

        # Print summary to console
        print("\n" + "="*80)
        print(validation_summary)
        print("="*80 + "\n")

        log("[SUCCESS] Step 00 complete")
        sys.exit(0)

    except Exception as e:
        log(f"[ERROR] {str(e)}")
        log("[TRACEBACK] Full error details:")
        with open(LOG_FILE, 'a', encoding='utf-8') as f:
            traceback.print_exc(file=f)
        traceback.print_exc()
        sys.exit(1)
