#!/usr/bin/env python3
# =============================================================================
# SCRIPT METADATA (Generated by g_code)
# =============================================================================
"""
Step ID: step03
Step Name: bootstrap_confidence_intervals
RQ: results/ch7/7.6.3
Generated: 2026-01-09

PURPOSE:
Compute 95% confidence intervals for ICC estimates using participant-level bootstrap
resampling. This quantifies uncertainty in ICC estimates and allows for statistical
comparison between domains.

EXPECTED INPUTS:
  - results/ch7/7.6.3/data/step01_domain_slopes.csv
    Columns: ['UID', 'slope_what', 'slope_where']
    Expected rows: 100
  - results/ch7/7.6.3/data/step02_variance_components.csv
    Columns: ['domain', 'variance_between', 'variance_total', 'n_participants']
    Expected rows: 2

EXPECTED OUTPUTS:
  - results/ch7/7.6.3/data/step03_bootstrap_cis.csv
    Columns: ['domain', 'icc_original', 'icc_boot_mean', 'ci_lower', 'ci_upper', 'boot_bias']
    Expected rows: 2 (What, Where)
  - results/ch7/7.6.3/data/step03_bootstrap_distributions.csv
    Columns: ['domain', 'bootstrap_iteration', 'icc_bootstrap']
    Expected rows: 2000 (1000 iterations x 2 domains)

VALIDATION CRITERIA:
  - All 1000 bootstrap iterations completed successfully
  - CI bounds in [0,1] for all domains
  - Bootstrap bias in [-0.1, 0.1] (acceptable range)
  - CI widths reasonable (typical for ICC)

g_code REASONING:
- Approach: Participant-level resampling with replacement, recalculate ICC for each sample
- Why this approach: Preserves correlation structure, appropriate for ICC uncertainty
- Data flow: Original slopes -> Bootstrap samples -> ICC distribution -> 95% CI
- Expected performance: ~5-10 seconds (1000 iterations)

IMPLEMENTATION NOTES:
- Analysis tool: tools.bootstrap.bootstrap_statistic
- Validation tool: Manual validation (bootstrap_stability expects different format)
- Parameters: n_bootstrap=1000, seed=42, confidence=0.95
- Method: Percentile method for CI construction
"""
# =============================================================================

import sys
from pathlib import Path
import pandas as pd
import numpy as np

# Add project root to path for imports
PROJECT_ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(PROJECT_ROOT))

# Import analysis tool
from tools.bootstrap import bootstrap_statistic

# =============================================================================
# Configuration
# =============================================================================

RQ_DIR = Path(__file__).resolve().parents[1]
LOG_FILE = RQ_DIR / "logs" / "step03_bootstrap_confidence_intervals.log"
OUTPUT_CIS = RQ_DIR / "data" / "step03_bootstrap_cis.csv"
OUTPUT_DIST = RQ_DIR / "data" / "step03_bootstrap_distributions.csv"

# Input files
INPUT_SLOPES = RQ_DIR / "data" / "step01_domain_slopes.csv"
INPUT_VAR = RQ_DIR / "data" / "step02_variance_components.csv"

# Bootstrap parameters
N_BOOTSTRAP = 1000
SEED = 42
CONFIDENCE = 0.95

# =============================================================================
# Logging Function
# =============================================================================

def log(msg):
    """Write to both log file and console."""
    with open(LOG_FILE, 'a', encoding='utf-8') as f:
        f.write(f"{msg}\n")
        f.flush()
    print(msg, flush=True)

# =============================================================================
# ICC Calculation Function
# =============================================================================

def calculate_icc(slope_values):
    """
    Calculate ICC(1,1) from slope values.

    For single observation per person:
    ICC = variance_between / variance_total

    Returns: float ICC value
    """
    variance_total = np.var(slope_values, ddof=1)
    variance_between = variance_total  # Single obs per person
    icc = variance_between / variance_total if variance_total > 0 else 0.0
    return icc

# =============================================================================
# Main Analysis
# =============================================================================

if __name__ == "__main__":
    try:
        log("[START] Step 03: Bootstrap Confidence Intervals")

        # =========================================================================
        # STEP 1: Load Data
        # =========================================================================

        log(f"[LOAD] Reading domain slopes...")
        df_slopes = pd.read_csv(INPUT_SLOPES)
        log(f"[LOADED] {len(df_slopes)} rows")

        log(f"[LOAD] Reading variance components...")
        df_var = pd.read_csv(INPUT_VAR)
        log(f"[LOADED] {len(df_var)} rows")

        # =========================================================================
        # STEP 2: Bootstrap ICC for Each Domain
        # =========================================================================
        # Resample participants with replacement, recalculate ICC
        # Repeat 1000 times to build bootstrap distribution

        log(f"[BOOTSTRAP] Parameters: n={N_BOOTSTRAP}, seed={SEED}, confidence={CONFIDENCE}")

        bootstrap_results = []
        bootstrap_distributions = []

        for domain in ['what', 'where']:
            col_name = f'slope_{domain}'
            slopes = df_slopes[col_name].values

            log(f"[{domain.upper()}] Starting bootstrap (1000 iterations)...")

            # Run bootstrap
            boot_result = bootstrap_statistic(
                data=slopes,
                statistic=calculate_icc,
                n_bootstrap=N_BOOTSTRAP,
                confidence=CONFIDENCE,
                seed=SEED
            )

            # Extract results
            icc_original = calculate_icc(slopes)
            icc_boot_mean = boot_result['statistic']  # CORRECTED: bootstrap_statistic returns 'statistic', not 'mean'
            ci_lower = boot_result['ci_lower']
            ci_upper = boot_result['ci_upper']
            boot_bias = icc_boot_mean - icc_original

            log(f"[{domain.upper()}] Original ICC: {icc_original:.4f}")
            log(f"[{domain.upper()}] Bootstrap mean: {icc_boot_mean:.4f}")
            log(f"[{domain.upper()}] 95% CI: [{ci_lower:.4f}, {ci_upper:.4f}]")
            log(f"[{domain.upper()}] Bootstrap bias: {boot_bias:.4f}")

            # Store summary
            bootstrap_results.append({
                'domain': domain.capitalize(),
                'icc_original': icc_original,
                'icc_boot_mean': icc_boot_mean,
                'ci_lower': ci_lower,
                'ci_upper': ci_upper,
                'boot_bias': boot_bias
            })

            # Store distribution
            bootstrap_samples = boot_result['bootstrap_samples']
            for i, icc_boot in enumerate(bootstrap_samples):
                bootstrap_distributions.append({
                    'domain': domain.capitalize(),
                    'bootstrap_iteration': i + 1,
                    'icc_bootstrap': icc_boot
                })

        # =========================================================================
        # STEP 3: Create Output DataFrames
        # =========================================================================

        df_cis = pd.DataFrame(bootstrap_results)
        df_dist = pd.DataFrame(bootstrap_distributions)

        log(f"[CREATED] Bootstrap CIs table: {len(df_cis)} rows")
        log(f"[CREATED] Bootstrap distributions table: {len(df_dist)} rows")

        # =========================================================================
        # STEP 4: Validate Bootstrap Results
        # =========================================================================

        log(f"[VALIDATE] Checking bootstrap results...")

        # Check all iterations completed
        expected_dist_rows = 2 * N_BOOTSTRAP  # 2 domains x 1000 iterations
        if len(df_dist) != expected_dist_rows:
            log(f"[ERROR] Expected {expected_dist_rows} bootstrap samples, got {len(df_dist)}")
            sys.exit(1)
        else:
            log(f"[PASS] All {N_BOOTSTRAP} iterations completed for both domains")

        # Check CI bounds in [0, 1]
        for _, row in df_cis.iterrows():
            domain = row['domain']
            if row['ci_lower'] < 0 or row['ci_upper'] > 1:
                log(f"[ERROR] {domain}: CI bounds outside [0, 1]")
                sys.exit(1)

        log(f"[PASS] All CI bounds in [0, 1]")

        # Check bootstrap bias acceptable
        for _, row in df_cis.iterrows():
            domain = row['domain']
            if abs(row['boot_bias']) > 0.1:
                log(f"[WARN] {domain}: Large bootstrap bias = {row['boot_bias']:.4f}")
            else:
                log(f"[PASS] {domain}: Bootstrap bias acceptable ({row['boot_bias']:.4f})")

        # =========================================================================
        # STEP 5: Save Results
        # =========================================================================

        log(f"[SAVE] Writing bootstrap CIs...")
        df_cis.to_csv(OUTPUT_CIS, index=False, encoding='utf-8')
        log(f"[SAVED] {OUTPUT_CIS} ({len(df_cis)} rows)")

        log(f"[SAVE] Writing bootstrap distributions...")
        df_dist.to_csv(OUTPUT_DIST, index=False, encoding='utf-8')
        log(f"[SAVED] {OUTPUT_DIST} ({len(df_dist)} rows)")

        log(f"[SUCCESS] Step 03 complete")
        log(f"[NEXT] Proceed to step04 (pairwise domain comparison)")

        sys.exit(0)

    except Exception as e:
        log(f"[ERROR] {str(e)}")
        log("[TRACEBACK] Full error details:")
        import traceback
        with open(LOG_FILE, 'a', encoding='utf-8') as f:
            traceback.print_exc(file=f)
        traceback.print_exc()
        sys.exit(1)
